import type { RegistryEntry } from "./types.ts";

/**
 * Renders COMPONENTS.md from component metadata. This file is the contract
 * agents read before writing a digest — it must stay cheap to read and
 * complete enough that reading component sources is unnecessary.
 */
export function renderCatalog(entries: RegistryEntry[]): string {
  const lines: string[] = [];

  lines.push("# component catalog");
  lines.push("");
  lines.push(
    "<!-- generated by `mandate-share build` from the `meta` export of each components/*.tsx file. do not edit by hand. -->",
  );
  lines.push("");
  lines.push(
    `${entries.length} components. use them in any \`digests/*.mdx\` file by tag name — no imports needed. ` +
      "every example below is compile-tested on each build. " +
      "to add a component, see the skill extension reference.",
  );
  lines.push("");
  lines.push("## quick index");
  lines.push("");
  lines.push("| component | use for |");
  lines.push("| --- | --- |");
  for (const { meta } of entries) {
    lines.push(`| [\`<${meta.name}>\`](#${meta.name.toLowerCase()}) | ${meta.description} |`);
  }
  lines.push("");

  for (const { meta, file } of entries) {
    lines.push(`## ${meta.name}`);
    lines.push("");
    lines.push(`${meta.description} (source: \`${file}\`)`);
    lines.push("");
    lines.push(`**when to use:** ${meta.whenToUse}`);
    if (meta.whenNotToUse) {
      lines.push("");
      lines.push(`**when not to use:** ${meta.whenNotToUse}`);
    }
    lines.push("");
    if (meta.props.length > 0) {
      lines.push("| prop | type | required | default | description |");
      lines.push("| --- | --- | --- | --- | --- |");
      for (const p of meta.props) {
        lines.push(
          `| \`${p.name}\` | \`${p.type}\` | ${p.required ? "yes" : "no"} | ${
            p.default !== undefined ? `\`${p.default}\`` : "—"
          } | ${p.description} |`,
        );
      }
    } else {
      lines.push("_no props — children only._");
    }
    lines.push("");
    lines.push("```mdx");
    lines.push(meta.example.trim());
    lines.push("```");
    lines.push("");
  }

  return lines.join("\n");
}
